site_name: CLADE Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
  logo: assets/clade-logo.png
  favicon: assets/clade-logo.png
nav:
  - Home: README.md
  - Benchmarking:
    - Home: benchmarking/1_index.md
    - TPC-DS: benchmarking/2_tpc-ds.md
    - Set up of TPC-DS: benchmarking/3_set-up.md
    - LST Bench: benchmarking/4_lst-bench.md

plugins:
  - search
  - bibtex:
      bib_file: "docs/refs.bib"
markdown_extensions:
  - footnotes
